# Generated by Django 5.0.3 on 2024-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Part Time'), ('Part Time', 'Full Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
