# Generated by Django 5.0.3 on 2024-03-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience_job_published_at_job_salaty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salaty',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
